[workspace]
members = [
    "nestor",
    "nestor-browser",
    "nestor-desktop",
    "nestor-sdl",
    "nestor-tauri",
]
resolver = "2"
exclude = []

[workspace.lints.clippy]
upper_case_acronyms = "allow"
