[package]
name = "nestor-sdl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nestor = { version = "0.1.0", path = "../nestor" }
sdl2 = "0.36.0"
